name: Build

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    name: Generate version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate.outputs.version }}
    steps:
      - id: generate
        run: echo "version=${{ github.run_number }}" >> "$GITHUB_OUTPUT"
    
  build:
    name: v${{ needs.version.outputs.version }}
    runs-on: ubuntu-latest
    needs: version
    env:
      VITE_APP_VERSION: ${{ needs.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./out