name: Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      target:
        required: true
        type: string
    secrets:
      credentials:
        required: true

jobs:
  deploy:
    name: ${{ inputs.target }}
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: google-application-credentials.json
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.repository_owner }}
          minimum-approvals: 1
          issue-title: 'Deploying v${{ inputs.version }} to ${{ inputs.target }}'
          issue-body: 'Please approve or deny the deployment of version v${{ inputs.version }} to target ${{ inputs.target }}.'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ./out

      - name: Print build contents
        shell: bash
        run: ls ./out

      - name: Replace variables
        shell: bash
        run: ./utils/replace-variables.sh ${{ inputs.target }}

      - name: Setup Google Application Credentials
        shell: bash
        run: echo "${{ secrets.credentials }}" | base64 --decode > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to ${{ inputs.target }}
        run: firebase use ${{ inputs.target }} && firebase deploy --only hosting,firestore

      - name: Remove Google Application Credentials
        if: success() || failure()
        run: rm ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
