name: Build and deploy stitcher

on:
  push:
    # Runs on pushes targeting the default branch
    branches: [$default-branch]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: npm

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build site
  #       run: npm run build:dev

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         path: ./out

  beta:
    name: Build & deploy beta
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.repository_owner }}
          minimum-approvals: 1
          issue-title: 'Deploying v${{ github.run_id }} to beta'
          issue-body: 'Please approve or deny the deployment of version v${{ github.run_id }}.'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build:beta

      - name: Deploy to stitcher-beta
        uses: w9jds/firebase-action@v13.7.5
        with:
          args: deploy --project=stitcher-beta --only hosting,firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STITCHER_BETA }}

  prod:
    name: Build & deploy prod
    runs-on: ubuntu-latest
    needs: beta
    permissions:
      contents: read
      issues: write
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ github.repository_owner }}
          minimum-approvals: 1
          issue-title: 'Deploying v${{ github.run_id }} to prod'
          issue-body: 'Please approve or deny the deployment of version v${{ github.run_id }}.'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build:prod

      - name: Deploy to stitcher-prod
        uses: w9jds/firebase-action@v13.7.5
        with:
          args: deploy --project=stitcher-prod-d457e --only hosting,firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STITCHER_PROD_D457E }}
