name: Build and deploy stitcher

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  VERSION: ${{ github.run_number }}

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      version: "$VERSION"

  beta:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      version: "$VERSION"
      target: beta
    secrets:
      credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BETA }}

  prod:
    name: Deploy
    needs: beta
    uses: ./.github/workflows/deploy.yml
    with:
      version: "$VERSION"
      target: prod
    secrets:
      credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PROD }}
