name: Build and deploy stitcher

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  beta:
    name: Deploy
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.build.outputs.version }}
      target: Beta
    secrets:
      credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BETA }}

  prod:
    name: Deploy
    needs: [build, beta]
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.build.outputs.version }}
      target: Production
    secrets:
      credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_PROD }}
